Remove obsolete includes added at https://crrev.com/c/4110828
The unguarded pcscan.h include breaks downstream WebRTC project: https://logs.chromium.org/logs/webrtc/buildbucket/cr-buildbucket/8794259521579445345/+/u/compile/stdout

Error log:
```
../../base/allocator/partition_allocator/starscan/pcscan.h:250:24: error: use of undeclared identifier 'StateBitmapFromAddr'
  auto* state_bitmap = StateBitmapFromAddr(slot_start);
```

Bug: b/263111771
Change-Id: I0fffdd4f843049790d466a72c59b23b4ef14476b
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4110796
Auto-Submit: Andrey Logvin <landrey@google.com>
Reviewed-by: Benoit Lize <lizeb@chromium.org>
Commit-Queue: Benoit Lize <lizeb@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1085504}
NOKEYCHECK=True
GitOrigin-RevId: e765367abe46b3d286f790902ed0066d8f14d1a8