Fix Android instrumentation tests not reporting exceptions when test listing fails
Before:
E  153.473s Main  Unrecognized error occurred.
Traceback (most recent call last):
  File "bin/../../../build/android/test_runner.py", line 952, in main
    return RunTestsCommand(args)
...
  File "/usr/local/google/code/clankium1/src/build/android/pylib/instrumentation/instrumentation_test_instance.py", line 262, in FilterTests
    raise MissingSizeAnnotationError(GetTestName(t))
MissingSizeAnnotationError: org.chromium.net.smoke.MissingNativeLibraryTest#initializationError: Test method is missing required size annotation. Add one of: @LargeTest, @Manual, @FlakyTest, @DisabledTest, @MediumTest, @SmallTest, @IntegrationTest, @EnormousTest

E    4.321s list_tests(86TX00E9L)  Unexpected output while listing tests:
E    4.322s list_tests(86TX00E9L)    Fatal exception when running tests
E    4.322s list_tests(86TX00E9L)    java.lang.RuntimeException: Failed on initializationError(org.chromium.net.smoke.MissingNativeLibraryTest)
E    4.322s list_tests(86TX00E9L)       at org.chromium.base.test.BaseChromiumAndroidJUnitRunner.listTests(BaseChromiumAndroidJUnitRunner.java:208)
E    4.322s list_tests(86TX00E9L)       at org.chromium.base.test.BaseChromiumAndroidJUnitRunner.onStart(BaseChromiumAndroidJUnitRunner.java:150)
E    4.322s list_tests(86TX00E9L)       at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
E    4.322s list_tests(86TX00E9L)    Caused by: java.lang.Exception: Custom runner class AndroidJUnit4ClassRunner should have a public constructor with signature AndroidJUnit4ClassRunner(Class testClass)
E    4.322s list_tests(86TX00E9L)       at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:111)
...

After: 
Change-Id: Ib6b304fbf675c205ca2d0e23bace17b81f2e18a9
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1691081
Reviewed-by: John Budorick <jbudorick@chromium.org>
Commit-Queue: Andrew Grieve <agrieve@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#676055}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: ff433dd42905a7c2e7e608d5cc0f3006306dee7a