Revert "Improve temp dir handling for child procs on Windows and macOS."
This reverts commit 8b4578d6a2e026524e4d2d751119538ad7f8fc19.

Reason for revert:
This change breaks running any tests on macOS systems that do *not* already have MAC_CHROMIUM_TMPDIR set; the generated value for it if it is unset is far too long (eg on my system it is "/var/folders/yd/p_tdv3gs24904_gjb44140tc003h8w/T/.org.chromium.Chromium.VHPP1z/0"), which hits the DCHECK here: https://cs.chromium.org/chromium/src/base/files/file_util_mac.mm?type=cs&q=MAC_CHROMIUM_TMPDIR&sq=package:chromium&g=0&l=35

To repro that failure:
1) build at trunk
2) $outdir/browser_tests

Original change's description:
> Improve temp dir handling for child procs on Windows and macOS.
> 
> Tests may leak files/directories in temp due to ScopedTempDir lifetime
> issues (see linked bug) or as a result of crashes. This CL augments the
> TestLauncher to handle such leaks a bit better. When launching a child
> proc on Windows and macOS, the TestLauncher now directs that child to
> its own dedicated temporary directory. Upon child exit, the launcher
> checks for leaked files/directories in that dir and deletes the dir. On
> test iteration completion, the launcher will emit a list of the tests
> that produced leaks when run with --test-launcher-print-temp-leaks that
> looks a lot like this:
> 
> ERROR: 2 files and/or directories were left behind in the temporary directory by one or more of these tests: PaymentManagerTest.ClearPaymentInstruments:PermissionControllerImplTest.ResettingOverridesForwardsReset:PermissionControllerImplTest.SettingOverridesForwardsUpdates:PermissionControllerImplTest.RequestPermissionsDelegatesIffMissingOverrides:PermissionControllerImplTest.GetPermissionStatusDelegatesIffNoOverrides:PermissionControllerImplTest.GetPermissionStatusForFrameDelegatesIffNoOverrides:PermissionControllerImplTest.NotifyChangedSubscriptionsCallsOnChangeOnly:PermissionControllerImplTest.PermissionsCannotBeOverriddenIfNotOverridable:PermissionControllerImplTest.GrantPermissionsReturnsStatusesBeingSetIfOverridable:PictureInPictureServiceImplTest.EnterPictureInPicture
> 
> Curious developers can binary search in that short list of tests to find
> the one(s) that are leaking and clean them up.
> 
> BUG=546640
> TBR=sky@chromium.org
> 
> Change-Id: If3be7034094827979c225d2eb2beba2d92e6e7ce
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1978679
> Commit-Queue: Greg Thompson <grt@chromium.org>
> Auto-Submit: Greg Thompson <grt@chromium.org>
> Reviewed-by: Erik Chen <erikchen@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#728475}

TBR=sky@chromium.org,erikchen@chromium.org,grt@chromium.org,isamsonov@google.com

# Not skipping CQ checks because original CL landed > 1 day ago.

Bug: 546640
Change-Id: Ic1d52021e5505508d271f2b1932f00c3e77377be
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1991933
Reviewed-by: Elly Fong-Jones <ellyjones@chromium.org>
Commit-Queue: Elly Fong-Jones <ellyjones@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#729487}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: de61628b1102c406efba127b1da8e52cb077a01d