win: Add missing process_handle.h include
Fixes the following error:

../../base/logging.cc(995,24): error: no member named 'GetUniqueIdForProcess' in namespace 'base'
      stream_ << base::GetUniqueIdForProcess() << ':';
                 ~~~~~~^
1 error generated.

Change-Id: Ibe3f11956ca491456685db446137b8e39248e696
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4294575
Reviewed-by: Lei Zhang <thestig@chromium.org>
Commit-Queue: Marshall Greenblatt <marshall@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1110671}
NOKEYCHECK=True
GitOrigin-RevId: 280eb4f65934f49a0c71d14bca52c31c11a64da6