Revert of [tracing] Throttle rate of heavy dumps and support to request light/heavy dumps (patchset #5 id:80001 of https://codereview.chromium.org/1267963002/ )
Reason for revert:
Suspect it breaks Linux telemetry tests (or possibly introduces flakiness):

Example https://build.chromium.org/p/chromium.linux/builders/Linux%20Tests/builds/28807

telemetry.internal.backends.chrome_inspector.tracing_backend_unittest.TracingBackendMemoryTest.testDumpMemorySuccess failed unexpectedly 0.2190s:
  Traceback (most recent call last):
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/telemetry/telemetry/internal/backends/chrome_inspector/tracing_backend_unittest.py", line 144, in testDumpMemorySuccess
      dump_id = self._browser.DumpMemory()
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/telemetry/telemetry/internal/browser/browser.py", line 291, in DumpMemory
      return self._browser_backend.DumpMemory(timeout)
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/telemetry/telemetry/internal/backends/chrome/chrome_browser_backend.py", line 321, in DumpMemory
      return self.devtools_client.DumpMemory(timeout)
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/telemetry/telemetry/internal/backends/chrome_inspector/devtools_client_backend.py", line 231, in DumpMemory
      return self._tracing_backend.DumpMemory(timeout)
    File "/mnt/data/b/build/slave/Linux_Tests/build/src/tools/telemetry/telemetry/internal/backends/chrome_inspector/tracing_backend.py", line 128, in DumpMemory
      'Tracing.requestMemoryDump:\n' + json.dumps(response, indent=2))
  TracingUnexpectedResponseException: Inspector returned unexpected response for Tracing.requestMemoryDump:
  {
    "id": 2,
    "error": {
      "message": "Tracing is not started",
      "code": -32603
    }
  }

Original issue's description:
> [tracing] Throttle rate of heavy dumps and support to request light/heavy dumps
>
> Currently all the dump providers dump detailed dumps every periodic
> dump. This makes the trace files huge. So, this CL throttles down the
> rate of heavy dumps of all the dump providers and removes temporary
> hacks. Along with this, this CL also adds support to request light and
> heavy dumps by adding MemoryDumpArgs as param to RequestGlobalDump()
>
> TBR=pfeldman@chromium.org
> BUG=499731
>
> Committed: https://crrev.com/33f2d3a5b276b70040adfd21edf364bd666b0aa2
> Cr-Commit-Position: refs/heads/master@{#342145}

TBR=petrcermak@chromium.org,nduca@chromium.org,pfeldman@chromium.org,ssid@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=499731

Review URL: https://codereview.chromium.org/1272703003

Cr-Original-Commit-Position: refs/heads/master@{#342167}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 563cc9718ff46295e59cb8b3e24df173275d2471