libstdc++: use max_align_t without std prefix in partition alloc constants.
Using std::max_align_t would require using cstddef instead of stddef.h. As
partition alloc constants is including stddef.h, let's remove the std::
namespace prefix.

This fixes this error building with libstdc++
../../base/allocator/partition_allocator/partition_alloc_constants.h:200:51: error: ‘max_align_t’ is not a member of ‘std’; did you mean ‘max_align_t’?

Bug: 957519
Change-Id: I72b22428937e7b7b1e6bb31fb0ac0bef3b72c581
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2423273
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Reviewed-by: Benoit L <lizeb@chromium.org>
Cr-Commit-Position: refs/heads/master@{#870443}
GitOrigin-RevId: 67e49c331f30ec0c9f76047acce3d55e97c3cf92