[base/task] Better compatibility with enable_base_tracing=false
Some WebRTC tests use //base with enable_base_tracing=false, and
recent changes to base/task/common/task_annotator.cc cause the following
compile error:

../../base/task/common/task_annotator.h:171:16: error: private field 'pending_task_' is not used [-Werror,-Wunused-private-field]
  PendingTask& pending_task_;
               ^
../../base/task/common/task_annotator.h:172:18: error: private field 'task_annotator_' is not used [-Werror,-Wunused-private-field]
  TaskAnnotator* task_annotator_;

Bug: None
Change-Id: I95568e6f969d6107c4c1146f1b47b0bfecced626
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4015625
Reviewed-by: Alexander Timin <altimin@chromium.org>
Reviewed-by: Harkiran Bolaria <hbolaria@google.com>
Reviewed-by: Mirko Bonadei <mbonadei@chromium.org>
Commit-Queue: Mirko Bonadei <mbonadei@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1071021}
NOKEYCHECK=True
GitOrigin-RevId: dcbb365486636049c12262a326d628547f73b8f7