Revert of Move logic from memory_mac to allocator_interception_mac. (patchset #5 id:80001 of https://codereview.chromium.org/2649973003/ )
Reason for revert:
This seems to be causing compile to fail on the Mac GPU FYI Asan bot, with error:
../../base/allocator/allocator_interception_mac.mm:320:3: error: use of undeclared identifier 'DeprotectMallocZone'
  DeprotectMallocZone(zone, &reprotection_start, &reprotection_length,
  ^
1 error generated.

See https://build.chromium.org/p/chromium.gpu.fyi/builders/Mac%20GPU%20ASAN%20Release/builds/1407/steps/compile/logs/stdio
and
https://build.chromium.org/p/chromium.gpu.fyi/builders/Mac%20GPU%20ASAN%20Release?numbuilds=100

Original issue's description:
> Move logic from memory_mac to allocator_interception_mac.
>
> This CL is a refactor and has no intended behavior changes.
>
> This CL moves the allocator interception logic from base/process/memory_mac.mm
> to base/allocator/allocator_interception_mac.mm in preparation for an
> implementation of the allocator shim.
>
> BUG=665567
>
> Review-Url: https://codereview.chromium.org/2649973003
> Cr-Commit-Position: refs/heads/master@{#446234}
> Committed: https://chromium.googlesource.com/chromium/src/+/9550b71347ce9acbe2875fb75ea46ec096230506

TBR=primiano@chromium.org,mark@chromium.org,erikchen@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=665567

Review-Url: https://codereview.chromium.org/2658083002
Cr-Original-Commit-Position: refs/heads/master@{#446346}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: e9942e23fec9e2bca8ebd70f79feb2120943b54b