Revert "Android: removing default execute() on AsyncTask"
This reverts commit be62a5bad9df35e97eab3fcdba50990c549e2304.

Reason for revert: Causes compile failure on many bots:

 ../../components/cronet/android/test/javaperftests/src/org/chromium/net/CronetPerfTestActivity.java:625: error: cannot find symbol
        new BenchmarkTask().execute();

https://ci.chromium.org/buildbot/chromium.android/Android%20Cronet%20Marshmallow%2064bit%20Perf/24049

Original change's description:
> Android: removing default execute() on AsyncTask
> 
> execute() is a confusing function, with a hidden implicit meaning that
> changed in API 11. It would be better if everyone had to use the more
> explicit executeOnExecutor() so their preference (serial or thread pool)
> is called out.
> 
> Bug: 869907
> Change-Id: I79be6d2b3114cb0520df1104ec5849f7c070c99e
> Reviewed-on: https://chromium-review.googlesource.com/1172446
> Reviewed-by: agrieve <agrieve@chromium.org>
> Commit-Queue: Sam Maier <smaier@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#584189}

TBR=agrieve@chromium.org,smaier@chromium.org

Change-Id: I9184afddb3028649c88f9fdf80ea46c4f7cc7806
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 869907
Reviewed-on: https://chromium-review.googlesource.com/1179352
Reviewed-by: Matthew Jones <mdjones@chromium.org>
Commit-Queue: Matthew Jones <mdjones@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#584211}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: da8490d633ae9609dc32fa9afdc1a5a83ce142e2