Add missing dependencies to //base:base_arc.
Otherwise building `chrome` target on a Mac flakily fails with below
errors depending on build action ordering.

Reproducible on a Mac via:
ninja -C out/default obj/base/base_arc/sys_string_conversions_mac.o

This causes these compile errors:
In file included from ../../base/strings/sys_string_conversions_mac.mm:5:
In file included from ../../base/strings/sys_string_conversions.h:17:
In file included from ../../base/strings/string_piece.h:19:
In file included from ../../base/check.h:15:
In file included from ../../base/location.h:13:
../../base/trace_event/base_tracing_forward.h:11:10: fatal error: 'base/tracing_buildflags.h' file not found

In file included from ../../base/strings/sys_string_conversions_mac.mm:13:
In file included from ../../base/mac/foundation_util.h:16:
../../base/logging.h:20:10: fatal error: 'base/logging_buildflags.h' file not found

In file included from ../../base/strings/sys_string_conversions_mac.mm:5:
In file included from ../../base/strings/sys_string_conversions.h:17:
In file included from ../../base/strings/string_piece.h:19:
In file included from ../../base/check.h:15:
In file included from ../../base/location.h:12:
In file included from ../../base/memory/raw_ptr_exclusion.h:11:
../../base/allocator/partition_allocator/pointers/raw_ptr_exclusion.h:11:10: fatal error: 'base/allocator/partition_allocator/partition_alloc_buildflags.h' file not found

In file included from ../../base/strings/sys_string_conversions_mac.mm:5:
In file included from ../../base/strings/sys_string_conversions.h:17:
In file included from ../../base/strings/string_piece.h:19:
In file included from ../../base/check.h:12:
../../base/dcheck_is_on.h:8:10: fatal error: 'base/debug/debugging_buildflags.h' file not found

Change-Id: I6d1e3a0067916e8b267030c88b821c814d06363c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4648531
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>
Commit-Queue: Philipp Wollermann <philwo@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Auto-Submit: Philipp Wollermann <philwo@google.com>
Cr-Commit-Position: refs/heads/main@{#1162885}
NOKEYCHECK=True
GitOrigin-RevId: aa19f428ef658b0b2918c6edb6e242bec9947a11