DanglingPtr: Fix DebugKv mismatching type.
The object stores a uint64_t, but its constructor takes `size_t`.

This is an issue on 32 bits systems where `size_t` is `uint32_t`.

This is an issue when enabling DanglingPointer detector:
https://chromium-review.googlesource.com/c/chromium/src/+/3870527/2
because `CountType` becomes `uint64_t`. It causes the macro
`PA_DEBUG_DATA_ON_STACK` to trigger the `c++11-narrowing` error:
```
../../base/allocator/partition_allocator/partition_ref_count.h:275:40:
error: non-constant-expression cannot be narrowed from type 'CountType'
(aka 'unsigned long long') to 'size_t' (aka 'unsigned int') in
initializer list [-Wc++11-narrowing]

    PA_DEBUG_DATA_ON_STACK("refcount", count);
                                       ^~~~~
```
https://ci.chromium.org/ui/p/chromium/builders/try/android-binary-size/1221029/overview

Bug: 1341550
Change-Id: I5412c3d4d5df041f613e82fef8d628e155e8a5bf
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3870924
Reviewed-by: Benoit Lize <lizeb@chromium.org>
Commit-Queue: Arthur Sonzogni <arthursonzogni@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1042624}
NOKEYCHECK=True
GitOrigin-RevId: 9616306eaf7e00601730239a8832b1dc5367e550