Revert of ShapeDetection: add support for Text Detection in Mac (patchset #4 id:80001 of https://codereview.chromium.org/2726843006/ )
Reason for revert:
../../services/shape_detection/text_detection_impl_mac.mm:68:8:
> error: 'CIRectangleFeature' is only available on macOS 10_10 or newer

Original issue's description:
> ShapeDetection: add support for Text Detection in Mac
>
> This CL adds text detection for Mac in services/shape_detection,
> and also adds unittest for it, that will be run, like the
> other specific unittests, in the mac gpu bots.
>
> BUG=697925
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.mac:mac_optional_gpu_tests_rel
> TEST= unittests that can be run anywhere like this:
> out/gn/service_unittests  --gtest_filter=*TextDetection* --use-gpu-in-tests
>
> and demo page, e.g.
> ./out/gn/Chromium.app/Contents/MacOS/Chromium  --enable-blink-features=ShapeDetection https://codepen.io/miguelao/full/ygxVqg
>
> Review-Url: https://codereview.chromium.org/2726843006
> Cr-Commit-Position: refs/heads/master@{#454609}
> Committed: https://chromium.googlesource.com/chromium/src/+/de6e85f0f4d505692f11c7f2d1c39f043f702796

TBR=rockot@chromium.org,reillyg@chromium.org,tsepez@chromium.org,mcasas@chromium.org
# Not skipping CQ checks because original CL landed more than 1 days ago.
BUG=697925

Review-Url: https://codereview.chromium.org/2728253003
Cr-Original-Commit-Position: refs/heads/master@{#454785}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 0832734083fedd1000e5e871071a78ff93b57a29