GCC: put attributes before function name in several failing function definitions in test_future.h
In GCC, in an inconsistent way, attributes are not allowed to be added
after function name in a function definition, if it is a template inside
a class. This breaks compilation in GCC.

Fixes build error:
  ../../base/compiler_specific.h:117:28: error: attributes are not allowed on a function-definition
    117 | #define WARN_UNUSED_RESULT __attribute__((warn_unused_result))
        |                            ^~~~~~~~~~~~~
  ../../base/test/test_future.h:156:75: note: in expansion of macro ‘WARN_UNUSED_RESULT’
    156 |   const typename std::tuple_element<I, std::tuple<Types...>>::type& Get() WARN_UNUSED_RESULT {
        |                                                                           ^~~~~~~~~~~~~~~~~~

This has been reported at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60625

Bug: 819294
Change-Id: I45de6af764739cc3b1628694425c67645c912e26
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3257941
Reviewed-by: François Doray <fdoray@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#937421}
NOKEYCHECK=True
GitOrigin-RevId: 38bb3db11df7a44143dd0b4df8f9abcaebc8b82f