Revert "Use the Windows MDM API to check if the machine is being managed."
This reverts commit ee0c03ddb4a10c8c9d14244bdefc8034054e846e.

Commit causes failures on Google Chrome ChromeOS and
Google Chrome Win:

../../components/update_client/utils.cc:171:39: error: 'IsEnterpriseManaged' is a private member of 'update_client::UpdaterState'
      if (attr.first != UpdaterState::IsEnterpriseManaged) {

BUG=690163
TBR=rogerta@chromium.org,sky@chromium.org,asvitkine@chromium.org,grt@chromium.org,avi@chromium.org,waffles@chromium.org,georgesak@chromium.org,pastarmovj@chromium.org

Review-Url: https://codereview.chromium.org/2710713004
Cr-Original-Commit-Position: refs/heads/master@{#452068}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: e4dd371c464f77b6fbef56d212f7de71e03bf002