SequenceBound: Move NO_SANITIZE annotation to fix GCC build
GCC seems to be stricter when it comes to the position of function
attributes, so move them around so the build works on both GCC and clang.

../../base/compiler_specific.h:158:27: error: attributes are not allowed on a function-definition
 #define NO_SANITIZE(what) __attribute__((no_sanitize(what)))
                           ^~~~~~~~~~~~~
../../base/threading/sequence_bound.h:114:33: note: in expansion of macro ‘NO_SANITIZE’
                 Args&&... args) NO_SANITIZE("cfi-unrelated-cast")
                                 ^~~~~~~~~~~
../../base/compiler_specific.h:158:27: error: attributes are not allowed on a function-definition
 #define NO_SANITIZE(what) __attribute__((no_sanitize(what)))
                           ^~~~~~~~~~~~~
../../base/threading/sequence_bound.h:162:37: note: in expansion of macro ‘NO_SANITIZE’
   void MoveRecordFrom(From&& other) NO_SANITIZE("cfi-unrelated-cast") {
                                     ^~~~~~~~~~~

Bug: 819294
Change-Id: Ic52ea4510ab34dac959e343cac869b32ba7005c5
Reviewed-on: https://chromium-review.googlesource.com/c/1456062
Auto-Submit: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Commit-Queue: Daniel Cheng <dcheng@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#629720}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 2ad12a1e735497b691c86dc98c0d31de97e6ff88