Revert "jni_generator: Revamp CLI"
This reverts commit 0324ff816d24325dcb5cf1348f52d4fe789954ee.

Reason for revert: #gardener Blocking CrOS uprev since https://crrev.com/c/4688602
jni_zero.py:138 "TypeError: __init__() got an unexpected keyword argument 'required'"

Bug: 1465241

Original change's description:
> jni_generator: Revamp CLI
>
> There is now one script with two subcommands:
>  * jni_zero.py generate-library (for jni_generator.py)
>  * jni_zero.py generate-final (for jni_registration_generator.py)
>
> Other changes:
> * Use hyphens in all flags names instead of _
> * Remove unused --cpp flag
> * Remove --ptr_type (we always set it to "long")
> * Rename --include -> --extra-include
> * Remove default value for 'javap' (to break a dep on build_utils.py)
> * Rename jni_generator_tests.py -> integration_tests.py
>
> Bug: 1406605
> Change-Id: Ie3018d6d50fc0051c39d82a580be4fd25a38f93d
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4685488
> Reviewed-by: Mohamed Heikal <mheikal@chromium.org>
> Commit-Queue: Andrew Grieve <agrieve@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1170630}

Bug: 1406605
Change-Id: I1b16d4ae07aeeb3e62e00fd25e7986fd6f699501
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4688700
Owners-Override: Trent Apted <tapted@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Trent Apted <tapted@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1171021}
NOKEYCHECK=True
GitOrigin-RevId: e4338c97c4e9d19c0aae6d0e5b9c07808b8b5c04