Fix compilation error encountered when DEBUG set to 1.
Fails to compiler if DEBUG is set to 1.  If DEBUG is 0 the error is hidden
because LOG_INFO() expands to an empty operation.

Fixes:
  ../../base/android/linker/linker_jni.cc:270:60: error: 'lib_basename' was not declared in this scope

BUG=390618

Review URL: https://codereview.chromium.org/375883002

git-svn-id: http://src.chromium.org/svn/trunk/src/base@281815 4ff67af0-8c30-449e-8e8b-ad334ec8d88c