[Android] Fix race condition when flag test overrides are unset
When the flag test values are unset while checking a test value, we
may get:

java.lang.NullPointerException: Attempt to read from field
'java.util.Map org.chromium.base.FeatureList$TestValues.mFeatureFlags'
on a null object reference

This works around the issue by storing the Map in a local variable
instead of getting it again from the static field. The better fix is
to lock down flag state and stop resetting it (crbug.com/1434471), but
it requires much more work to change existing tests that rely on it.

Bug: 1494095
Change-Id: I76a18c73fa2ef7013f8b8d59c472293b3e2d90c0
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5054624
Code-Coverage: findit-for-me@appspot.gserviceaccount.com <findit-for-me@appspot.gserviceaccount.com>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Commit-Queue: Henrique Nakashima <hnakashima@chromium.org>
Reviewed-by: Calder Kitagawa <ckitagawa@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1228520}
NOKEYCHECK=True
GitOrigin-RevId: 1a207b4441b0332afe5b0d329fe549a8d43973ee