win/swarming: Make 64-bit debug component builds work on swarming?
After https://codereview.chromium.org/896583002/, the isolate step on the
64-bit bot is failing with

    MappingError: Input file C:\b\build\slave\CrWinClang64_dbg_\build\src\out\Debug_x64\x64\msvcp120d.dll doesn't exist

It looks like the x64\msvcp120d.dll only exists in 32-bit builds.
While here, also add the x64 libraries for 32-bit release builds.

BUG=453657,452057
R=maruel@chromium.org, scottmg@chromium.org

Review URL: https://codereview.chromium.org/897713002

Cr-Original-Commit-Position: refs/heads/master@{#314410}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 8d81593b1a531d950261cbb0d48cdf8464aae442