Fix intrusive_heap.h build when exceptions are enabled.
This not visible in default chromium setup since it disables exceptions
by default. The code does however fail to compile if one enables them:

../../base/containers/intrusive_heap.h:717:48: error: 'operator=' is missing exception specification 'noexcept'
IntrusiveHeap<T, Compare, HeapHandleAccessor>::operator=(
                                               ^
../../base/containers/intrusive_heap.h:290:18: note: previous declaration is here
  IntrusiveHeap& operator=(IntrusiveHeap&&) noexcept;

Change-Id: I8c633333ae17002ba0b643e6c88e463d28de0086
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1815862
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: Piotr Tworek <ptworek@vewd.com>
Cr-Original-Commit-Position: refs/heads/master@{#699661}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: d062f7bceb95d14054fbe14ba9f65f8095b421fc