Fix missing <algorithm> include for std::min
This error reproduces on Windows when building with
use_custom_libcxx=false.

../..\base/strings/string_piece.h(218,35): error: no member named 'min' in namespace 'std'
    const size_type rcount = std::min(count, size() - pos);
                             ~~~~~^

Change-Id: I353ea33656049b94a5f82a9480a4d011b40fa81e
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3238990
Reviewed-by: Gabriel Charette <gab@chromium.org>
Commit-Queue: Gabriel Charette <gab@chromium.org>
Cr-Commit-Position: refs/heads/main@{#934695}
NOKEYCHECK=True
GitOrigin-RevId: ce8d514d27bf2714a99f544ca1116f03bd382ce0