GCC: move NO_SANITIZE in PCScanTask::ScanPartition to the start.
GCC build breaks because we are declaring an attribute in the wrong
place of a function definition:
../../base/compiler_specific.h:125:27: error: attributes are not allowed on a function-definition
  125 | #define NO_SANITIZE(what) __attribute__((no_sanitize(what)))
      |                           ^~~~~~~~~~~~~
../../base/allocator/partition_allocator/pcscan.cc:221:57: note: in expansion of macro ‘NO_SANITIZE’
  221 | size_t PCScan<thread_safe>::PCScanTask::ScanPartition() NO_SANITIZE("thread") {
      |                                                         ^~~~~~~~~~~

Bug: 819294
Change-Id: Iff1a3ec8c4b2765c7d95c45a1951fa7f0714a86c
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2485545
Reviewed-by: Tom Sepez <tsepez@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#819268}
GitOrigin-RevId: 6d3919c7f0396e85f615737ed27a3e46adae2c61