registry: Add missing noexcept specifier
Seems to be required in C++17 mode.

../../base/win/registry.cc(109,9): error: 'RegKey' is missing exception specification 'noexcept' [-Werror,-Wmicrosoft-exception-spec]
RegKey::RegKey(RegKey&& other)
        ^
                               noexcept
../..\base/win/registry.h(41,3): note: previous declaration is here
  RegKey(RegKey&& other) noexcept;
  ^

Bug: 752720
Change-Id: I3d98b80ea3c9831e3a4ba5f2ca6e8f69800f1d80
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2089840
Auto-Submit: Raul Tambre <raul@tambre.ee>
Reviewed-by: Bruce Dawson <brucedawson@chromium.org>
Commit-Queue: Raul Tambre <raul@tambre.ee>
Cr-Original-Commit-Position: refs/heads/master@{#748041}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 52bb9bcf55601233224f95d162c028be0f5b0503