Fix IsContiguousIterator with a function pointer under C++20.
C++20 removes iterator_traits<T*> specialization when T is not an
object type (such as a function pointer). And std::iter_value_t<T*> as
a result is also not defined when T is not an object.

Our current backport of iter_value_t is always defined, which differs
from C++20. And our IsContiguousIterator type trait depends on it always
existing, which breaks when we enable C++20.

So we:

1) Fix out iter_value_t to be closer to C++20. Using it for a function
pointer results in a compilation error due to a missing "value_type"
member in a proxy type for iterator_traits.

2) Fix IsContiguousIterator to not rely on iter_value_t existing when
the type is a pointer to a non-object type. We must stop using
std::conjunction, as it does not short circuit. And we must override
PointsToObject for T* to verity T is an object before we use
iter_value_t<T*>.

With 1) but not 2) we get a similar error to turning on C++20, where the
ContiguousIterator tests fail for function pointers:

../../base/template_util.h:369:63: error: no type named 'value_type' in 'base::IterValuePointerImpl<void (*)(), false>'
      typename IterValuePointerImpl<T*, std::is_object_v<T>>::value_type;
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
../../base/template_util.h:373:1: note: in instantiation of template class 'base::IterValueImpl<void (*)()>' requested here
using iter_value_t = typename IterValueImpl<remove_cvref_t<Iter>>::value_type;
^
../../base/containers/contiguous_iterator.h:42:52: note: in instantiation of template type alias 'iter_value_t' requested here
template <typename T, typename ArrayT = std::array<iter_value_t<T>, 1>>
                                                   ^
../../base/containers/contiguous_iterator.h:87:19: note: in instantiation of default argument for 'IsArrayIter<void (*)()>' required here
                  IsArrayIter<T>,
                  ^~~~~~~~~~~~~~
../../base/containers/contiguous_iterator.h:105:7: note: in instantiation of template class 'base::internal::IsContiguousIteratorImpl<void (*)(), true>' requested here
    : internal::IsContiguousIteratorImpl<remove_cvref_t<T>> {};
      ^
../../base/containers/contiguous_iterator_unittest.cc:109:18: note: in instantiation of template class 'base::IsContiguousIterator<void (*)()>' requested here
  static_assert(!IsContiguousIterator<void (*)()>::value,
                 ^

R=jdoerrie@chromium.org

Bug: 1284275
Change-Id: I1fe4b8950194aabf163e8234ad3328d9ec509f40
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3626389
Reviewed-by: Jan Wilken Dörrie <jdoerrie@chromium.org>
Commit-Queue: danakj <danakj@chromium.org>
Cr-Commit-Position: refs/heads/main@{#999374}
NOKEYCHECK=True
GitOrigin-RevId: 6948b872526db78d86b4f6de3922ad513519f1cb