GCC: default move constructor of ServiceWorkerRunningInfo noexcept requires StrongAlias noexcept too.
Fix for this GCC compilation error:
../../content/public/browser/service_worker_running_info.cc:26:1: error: function ‘content::ServiceWorkerRunningInfo::ServiceWorkerRunningInfo(content::ServiceWorkerRunningInfo&&)’ defaulted on its redeclaration with an exception-specification that differs from the implicit exception-specification ‘’
   26 | ServiceWorkerRunningInfo::ServiceWorkerRunningInfo(
      | ^~~~~~~~~~~~~~~~~~~~~~~~

Problem comes from blink::ServiceWorkerToken move constructor being declared
noexcept, but its parent StrongAlias not having noexcept.

Fix making StrongAlias move constructor noexcept too.

Bug: 819294
Change-Id: I127a435b3d1f52f01a40700457ce6e67d5d67af2
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2359077
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#800495}
GitOrigin-RevId: e4b5d6eddf876509c05cb377bc4ce67fae0f3b1c