Revert "Reland "Add trace events to debug hangs from the field""
This reverts commit 7e9da16ac1f0d7fc0996b46d2eef04e878ad9512.

Reason for revert: Broken roll deps here:
  https://webrtc-review.googlesource.com/c/src/+/259800/

[570/616] CXX obj/base/base/hang_watcher.o
FAILED: obj/base/base/hang_watcher.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
../../base/threading/hang_watcher.cc:745:38: error: no member named 'Track' in namespace 'perfetto'
const auto track = perfetto::Track::FromPointer(
~~~~~~~~~~^
../../base/threading/hang_watcher.cc:746:19: error: no member named 'ThreadTrack' in namespace 'perfetto'; did you mean 'ThreadTicks'?
this, perfetto::ThreadTrack::ForThread(thread_id));
^~~~~~~~~~~~~~~~~~~~~
ThreadTicks
../../base/time/time.h:1124:19: note: 'ThreadTicks' declared here

Original change's description:
> Reland "Add trace events to debug hangs from the field"
>
> This is a reland of commit 7315f725dfbeb6362a88d52097fcc5764dde043d
>
> The compilation error was due to a limitation to capture a
> reference from a structured-binding.
>
> see: https://stackoverflow.com/questions/46114214/lambda-implicit-capture-fails-with-variable-declared-from-structured-binding
>
>
> Original change's description:
> > Add trace events to debug hangs from the field
> >
> > This CL is adding trace events to exposed the Hung state into traces.
> >
> > The goal is to collect traces from the field and try to understand
> > under which circumstances these hangs occurred.
> >
> > Bug: 1310011
> > Change-Id: Iece050de0a247ce688c2c6744790ed3343c33ae4
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3587246
> > Reviewed-by: Francois Pierre Doray <fdoray@chromium.org>
> > Commit-Queue: Etienne Bergeron <etienneb@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#992703}
>
> Bug: 1310011
> Change-Id: I128aff45ca0cfbfe5a332e7df1d488bd5bca734e
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3594381
> Reviewed-by: Francois Pierre Doray <fdoray@chromium.org>
> Commit-Queue: Etienne Bergeron <etienneb@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#994366}

Bug: 1310011
Change-Id: I3ef16044e6949f01ac360866013d4dabcc8ee9cf
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3600278
Auto-Submit: Etienne Bergeron <etienneb@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Chris Hamilton <chrisha@chromium.org>
Reviewed-by: Francois Pierre Doray <fdoray@chromium.org>
Commit-Queue: Francois Pierre Doray <fdoray@chromium.org>
Cr-Commit-Position: refs/heads/main@{#995211}
NOKEYCHECK=True
GitOrigin-RevId: 2a9427db5604a22e5c7bcfaa746dcfb4fe02c521