MTECheckedPtr: Untag in `GetDeltaElems()`
`ExtractTag()` expects a `uintptr_t`; untagging to get back this type
is needed to fulfill this. Compilation fails otherwise:

``` none
In file included from ../../base/memory/raw_ptr_unittest.cc:5:
../../base/memory/raw_ptr.h:287:22: error: cannot initialize a parameter
of type 'uintptr_t' (aka 'unsigned long') with an lvalue of type 'int *'
    CHECK(ExtractTag(wrapped_ptr1) == ExtractTag(wrapped_ptr2));
```

Bug: 1364476
Change-Id: I47c9e4e4fe08ad2ba2b19dfa5a7d7597898f4bc7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3901048
Commit-Queue: Kalvin Lee <kdlee@chromium.org>
Reviewed-by: Bartek Nowierski <bartekn@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1047901}
NOKEYCHECK=True
GitOrigin-RevId: 89ccdde90c5ac5690bbc10a6f4b9c6157ee79733