Fix the build when DCHECK_IS_CONFIGURABLE is used
We have to check with define() whether the variable is defined instead
looking at its value as it couldn't be defined. It's defined with:

    if (dcheck_is_configurable) {
      defines += [ "DCHECK_IS_CONFIGURABLE=1" ]
    }

And the compilation failure:

In file included from gen/modules/desktop_capture/linux/pipewire_stubs.cc:3:
In file included from gen/modules/desktop_capture/linux/pipewire_stubs.h:11:
../../base/logging.h:846:5: error: 'DCHECK_IS_CONFIGURABLE' is not defined, evaluates to 0 [-Werror,-Wundef]
    ^
\#if DCHECK_IS_CONFIGURABLE

Change-Id: I85137252cb3ebd6965037b747574804a3c837f40
Reviewed-on: https://chromium-review.googlesource.com/c/1312948
Reviewed-by: Scott Violet <sky@chromium.org>
Reviewed-by: Thomas Anderson <thomasanderson@chromium.org>
Commit-Queue: Tomáš Popela <tomas.popela@gmail.com>
Cr-Original-Commit-Position: refs/heads/master@{#606230}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 4152df92da08a032aa0be01a3d3cafda5d9a6e4f