better error messaging for un-updated vs2012
another attempt at making it more clear what's going on for random bots.

if it's out of date, the compiler will output something like this now:

Relevant defines:
#define _M_IX86 600
#define _MSC_FULL_VER 170051106
Visual Studio 2012 x86 must be updated to at least Update 1
d:\src\cr\src\base\win\win_util.cc(353) : fatal error C1004: unexpected end-of-file found

R=cpu@chromium.org

Review URL: https://codereview.chromium.org/12780006

git-svn-id: http://src.chromium.org/svn/trunk/src/base@188509 4ff67af0-8c30-449e-8e8b-ad334ec8d88c