Make scoped_refptr constexpr default constructible.
Just like std::unique_ptr and std::shared_ptr.

Remove support for opaque types in scoped_refptr. These weren't used
anywhere and already strongly discouraged.
"constexpr" implies "inline" and as such template instantiation being
out-of-line in a single translation unit makes it invisible to other
translation units which expect to have its full definition (per
"inline"), generating errors like the following:
FAILED: obj/base/x64/base_unittests
Undefined symbols for architecture x86_64:
  "scoped_refptr<base::OpaqueRefCounted>::scoped_refptr()", referenced from:
      RefCountedUnitTest_ScopedRefPtrToOpaque_Test::TestBody() in ref_counted_unittest.o
  "scoped_refptr<base::OpaqueRefCountedThreadSafe>::scoped_refptr()", referenced from:
      RefCountedUnitTest_ScopedRefPtrToOpaqueThreadSafe_Test::TestBody() in ref_counted_unittest.o
ld: symbol(s) not found for architecture x86_64

Not supporting opaque types is a fallout of scoped_refptr needing to know
the type is a subclass of RefCounted(ThreadSafe). Workarounds have already
been attempted and failed.

Prior discussion and conclusion to discourage their usage :
https://groups.google.com/a/chromium.org/d/topic/chromium-dev/0khIRhxDq6E/discussion

Bug: 800760
Change-Id: I1a413cad642e1703f4722dc597a91436f6c0c711
Reviewed-on: https://chromium-review.googlesource.com/863671
Commit-Queue: Gabriel Charette <gab@chromium.org>
Reviewed-by: Daniel Cheng <dcheng@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#529283}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: e73967a0699e1e8af0554735822abb2985c52a73