[Android] Add more exceptions to PiiELider
ClassNotFoundException and NoClassDefFoundError point to missing classes
which fail to be realised as classes by PiiElider since it checks that
by trying to load the class. Also added com.chrome to app namespace
since resources are namespaced by the apk package which starts with
com.chrome.

Bug: 1265948
Change-Id: I2979a2b5c359a075572d04aa889d8d5436de4083
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3282084
Commit-Queue: Mohamed Heikal <mheikal@chromium.org>
Auto-Submit: Mohamed Heikal <mheikal@chromium.org>
Reviewed-by: Peter Wen <wnwen@chromium.org>
Reviewed-by: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/main@{#942280}
NOKEYCHECK=True
GitOrigin-RevId: 19895b8311bee248dfc19936dde2a811dac4b2f8