[base] Improve errors when binding callbacks to an overloaded function
It is not possible to use `base::BindOnce()` or `base::BindRepeating()`
on some overloaded function F without disambiguating it some way.
Internally, binding a function takes an address to the function, but
with an overloaded function, the compiler will not know which address
to select unless it is disambiguated in some way.

However, clang does not provide a helpful error in this situation and
simply complains that none of the overloads for `base::BindOnce()` (or
`base::BindRepeating()`) could be used, without highlighting the fact
that the root cause is that the address of the overloaded function F
cannot be taken.

To fix this, add a new catchall overload for `BindOnce()` and
`BindRepeating()` which only matches if template argument inference
fails due to how overload resolution works (any standard or
user-defined conversion sequence is always better than an ellipsis
conversion sequence).

The resulting error message more clearly highlights that the address of
an overloaded function is being used:

../../base/bind_unittest.cc:1745:32: error: reference to overloaded
function could not be resolved; did you mean to call it with no
arguments?
  decltype(auto) cb = BindOnce(&F);
                               ^~
../../base/bind_unittest.cc:1743:6: note: possible target for call
void F(int);
     ^
../../base/bind_unittest.cc:1742:6: note: possible target for call
void F();
     ^

Depending on the specific situation, it is still possible to have a few
spurious errors, but it should still be an overall improvement.

As incidental cleanup, the specializations of `BindOnce()` and
`BindRepeating()` that special-cased re-binding a callback with no
additional parameters have been moved down into BindImpl(). Originally,
the intent here was to limit the number of `base::BindOnce()` and
`base::BindRepeating()` overloads to improve the precision of errors;
it turns out this is not necessary, but it still seems like a nice
improvement to move this optimization detail out of the public
interface.

Change-Id: Ife73cb354157ee5cc0051e6cea7336392835c4f7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3126587
Reviewed-by: Dominic Farolino <dom@chromium.org>
Commit-Queue: Daniel Cheng <dcheng@chromium.org>
Cr-Commit-Position: refs/heads/main@{#922690}
NOKEYCHECK=True
GitOrigin-RevId: 58ea45b7087ec19f04c7e066d1fc3626b910b07a